#check the below link
https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#:~:text=To%20create%20a%20non%2Dexpiring,with%20that%20generated%20token%20data
#copy secret.yml  i maked it as svc-secret.yml
  
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: mysecretname
  annotations:
    kubernetes.io/service-account.name: jenkins    
	
	#create this secret inside a namespace we already creataed called webapps
  #and run the below commands
	
	$kubectl apply -f svc-secret.yml -n webapps
	
	$kubectl -n webapps describe secret mysecretname

  #it will generate a token save it in a safezone